title: CV | A jekyll template
description:  A beautiful template for your CV.
# url: https://jekyll-cv.stavrospanakakis.com
url: https://hmin-ab.github.io/hmin-cv
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
